const express = require('express');
const { Product_controller } = require('../../../controller');
const upload = require('../../../middleware/upload');
const auth = require('../../../middleware/auth');
const router = express.Router();

//localhost:8000/api/v1/product/get-product
router.get(
    '/get-product',
    Product_controller.getProduct
)

//localhost:8000/api/v1/product/list-product
router.get(
    '/list-product',
    Product_controller.listproduct
)

router.get(
    '/getSubByCat/:id',
    Product_controller.getSubByCat
)

//localhost:8000/api/v1/product/get_all-product
router.get(
    '/get_all-product',
    Product_controller.getAll_product
)

//localhost:8000/api/v1/product/post-product
router.post(
    '/post-product',
    upload.single('product_img'),
    Product_controller.addProduct
)

//localhost:8000/api/v1/product/put-product/:id
router.put(
    '/put-product/:id',
    auth(["admin","employee"]),
    upload.single('product_img'),
    Product_controller.putProduct
)

//localhost:8000/api/v1/product/delete-product/:id
router.delete(
    '/delete-product/:id',
    auth(["admin","employee"]),
    Product_controller.deleteProduct
)

// --------------------------------------------------------------------------------------------------

// /products/search/?data                      //Retrieve the product using sortOrder, rating, max, min, category, page = 1, limit = 10)
//localhost:8000/api/v1/product/searchProduct
router.get(
    '/searchProduct',
    Product_controller.searchProduct
)

// /products/list/category/{category_id}                   //Retrieve products by category
// localhost:8000/api/v1/product/product-by-cat/:id
router.get(
    '/product-by-cat/:id',
    Product_controller.product_by_cat
)

// /products/list/subcategory/{subcategory_id}             //Retrieve products by subcategory
// localhost:8000/api/v1/product/product-by-subcat/:id
router.get(
    '/product-by-subcat/:id',
    Product_controller.product_by_subcat
)

// /products/new-arrivals                                  //Retrieve recently added products.
// localhost:8000/api/v1/product/new-add-product
router.get(
    '/new-add-product',
    Product_controller.new_add_product
)

// /products/count-categories                  //Retrieve the count of products for each category.
// localhost:8000/api/v1/product/count-product-cat
router.get(
    '/count-product-cat',
    Product_controller.count_product_by_cat
)

// -----------------------------exam-----------------------------------//

// 1.Retrieve categories with the highest total sales.
// localhost:8000/api/v1/product/highest-sales
router.get(
    '/highest-sales',
    Product_controller.highest_sales
)

// 2. Retrieve total revenue generated by each subcategory.
// localhost:8000/api/v1/product/revenue-subcategory
router.get(
    '/revenue-subcategory',
    Product_controller.revenue_subcategory
)

// 3. Retrieve products with the highest number of reviews.
// localhost:8000/api/v1/product/High-reviews
router.get(
    '/High-reviews',
    Product_controller.High_reviews
)


module.exports = router

